spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/ordersys?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  # 显示 SQL 语句
  jpa:
    show-sql: true
  jackson:
    time-zone: GMT+8
server:
  context-path: /sell
  port: 8080
